APIDOC_SRC=\
	$T/include/xapian.h\
	$T/include/xapian/attributes.h\
	$T/include/xapian/compactor.h\
	$T/include/xapian/constants.h\
	$T/include/xapian/constinfo.h\
	$T/include/xapian/database.h\
	$T/include/xapian/dbfactory.h\
	$T/include/xapian/deprecated.h\
	$T/include/xapian/derefwrapper.h\
	$T/include/xapian/document.h\
	$T/include/xapian/enquire.h\
	$(top_builddir)/include/xapian/error.h\
	$T/include/xapian/errorhandler.h\
	$T/include/xapian/eset.h\
	$T/include/xapian/expanddecider.h\
	$T/include/xapian/geospatial.h\
	$T/include/xapian/intrusive_ptr.h\
	$T/include/xapian/iterator.h\
	$T/include/xapian/keymaker.h\
	$T/include/xapian/matchspy.h\
	$T/include/xapian/mset.h\
	$T/include/xapian/positioniterator.h\
	$T/include/xapian/postingiterator.h\
	$T/include/xapian/postingsource.h\
	$T/include/xapian/query.h\
	$T/include/xapian/queryparser.h\
	$T/include/xapian/registry.h\
	$T/include/xapian/stem.h\
	$T/include/xapian/termgenerator.h\
	$T/include/xapian/termiterator.h\
	$T/include/xapian/types.h\
	$T/include/xapian/unicode.h\
	$T/include/xapian/valueiterator.h\
	$T/include/xapian/valuesetmatchdecider.h\
	$(top_builddir)/include/xapian/version.h\
	$T/include/xapian/visibility.h\
	$T/include/xapian/weight.h
SOURCEDOC_SRC=\
	$T/api/compactor.cc\
	$T/api/constinfo.cc\
	$T/api/decvalwtsource.cc\
	$T/api/documentterm.h\
	$T/api/documentvaluelist.cc\
	$T/api/documentvaluelist.h\
	$T/api/editdistance.cc\
	$T/api/editdistance.h\
	$T/api/emptypostlist.cc\
	$T/api/emptypostlist.h\
	$T/api/error.cc\
	$T/api/errorhandler.cc\
	$T/api/expanddecider.cc\
	$T/api/keymaker.cc\
	$T/api/leafpostlist.cc\
	$T/api/leafpostlist.h\
	$T/api/maptermlist.h\
	$T/api/matchspy.cc\
	$T/api/omdatabase.cc\
	$T/api/omdocument.cc\
	$T/api/omenquire.cc\
	$T/api/omenquireinternal.h\
	$T/api/positioniterator.cc\
	$T/api/postingiterator.cc\
	$T/api/postingsource.cc\
	$T/api/postlist.cc\
	$T/api/postlist.h\
	$T/api/query.cc\
	$T/api/queryinternal.cc\
	$T/api/queryinternal.h\
	$T/api/queryvector.h\
	$T/api/registry.cc\
	$T/api/replication.cc\
	$T/api/replication.h\
	$T/api/smallvector.cc\
	$T/api/smallvector.h\
	$T/api/sortable-serialise.cc\
	$T/api/termiterator.cc\
	$T/api/termlist.cc\
	$T/api/termlist.h\
	$T/api/valueiterator.cc\
	$T/api/valuerangeproc.cc\
	$T/api/valuesetmatchdecider.cc\
	$T/api/vectortermlist.cc\
	$T/api/vectortermlist.h\
	$T/backends/alltermslist.cc\
	$T/backends/alltermslist.h\
	$T/backends/backends.h\
	$T/backends/byte_length_strings.h\
	$T/backends/chert/chert_alldocsmodifiedpostlist.cc\
	$T/backends/chert/chert_alldocsmodifiedpostlist.h\
	$T/backends/chert/chert_alldocspostlist.cc\
	$T/backends/chert/chert_alldocspostlist.h\
	$T/backends/chert/chert_alltermslist.cc\
	$T/backends/chert/chert_alltermslist.h\
	$T/backends/chert/chert_btreebase.cc\
	$T/backends/chert/chert_btreebase.h\
	$T/backends/chert/chert_check.cc\
	$T/backends/chert/chert_check.h\
	$T/backends/chert/chert_compact.cc\
	$T/backends/chert/chert_cursor.cc\
	$T/backends/chert/chert_cursor.h\
	$T/backends/chert/chert_database.cc\
	$T/backends/chert/chert_database.h\
	$T/backends/chert/chert_databasereplicator.cc\
	$T/backends/chert/chert_databasereplicator.h\
	$T/backends/chert/chert_dbcheck.cc\
	$T/backends/chert/chert_dbcheck.h\
	$T/backends/chert/chert_dbstats.cc\
	$T/backends/chert/chert_dbstats.h\
	$T/backends/chert/chert_document.cc\
	$T/backends/chert/chert_document.h\
	$T/backends/chert/chert_lazytable.h\
	$T/backends/chert/chert_metadata.cc\
	$T/backends/chert/chert_metadata.h\
	$T/backends/chert/chert_modifiedpostlist.cc\
	$T/backends/chert/chert_modifiedpostlist.h\
	$T/backends/chert/chert_positionlist.cc\
	$T/backends/chert/chert_positionlist.h\
	$T/backends/chert/chert_postlist.cc\
	$T/backends/chert/chert_postlist.h\
	$T/backends/chert/chert_record.cc\
	$T/backends/chert/chert_record.h\
	$T/backends/chert/chert_replicate_internal.h\
	$T/backends/chert/chert_spelling.cc\
	$T/backends/chert/chert_spelling.h\
	$T/backends/chert/chert_spellingwordslist.cc\
	$T/backends/chert/chert_spellingwordslist.h\
	$T/backends/chert/chert_synonym.cc\
	$T/backends/chert/chert_synonym.h\
	$T/backends/chert/chert_table.cc\
	$T/backends/chert/chert_table.h\
	$T/backends/chert/chert_termlist.cc\
	$T/backends/chert/chert_termlist.h\
	$T/backends/chert/chert_termlisttable.cc\
	$T/backends/chert/chert_termlisttable.h\
	$T/backends/chert/chert_types.h\
	$T/backends/chert/chert_valuelist.cc\
	$T/backends/chert/chert_valuelist.h\
	$T/backends/chert/chert_values.cc\
	$T/backends/chert/chert_values.h\
	$T/backends/chert/chert_version.cc\
	$T/backends/chert/chert_version.h\
	$T/backends/contiguousalldocspostlist.cc\
	$T/backends/contiguousalldocspostlist.h\
	$T/backends/database.cc\
	$T/backends/database.h\
	$T/backends/databasereplicator.cc\
	$T/backends/databasereplicator.h\
	$T/backends/dbcheck.cc\
	$T/backends/dbfactory.cc\
	$T/backends/dbfactory_remote.cc\
	$T/backends/document.h\
	$T/backends/flint_lock.cc\
	$T/backends/flint_lock.h\
	$T/backends/glass/glass_alldocspostlist.cc\
	$T/backends/glass/glass_alldocspostlist.h\
	$T/backends/glass/glass_alltermslist.cc\
	$T/backends/glass/glass_alltermslist.h\
	$T/backends/glass/glass_changes.cc\
	$T/backends/glass/glass_changes.h\
	$T/backends/glass/glass_check.cc\
	$T/backends/glass/glass_check.h\
	$T/backends/glass/glass_compact.cc\
	$T/backends/glass/glass_cursor.cc\
	$T/backends/glass/glass_cursor.h\
	$T/backends/glass/glass_database.cc\
	$T/backends/glass/glass_database.h\
	$T/backends/glass/glass_databasereplicator.cc\
	$T/backends/glass/glass_databasereplicator.h\
	$T/backends/glass/glass_dbcheck.cc\
	$T/backends/glass/glass_dbcheck.h\
	$T/backends/glass/glass_defs.h\
	$T/backends/glass/glass_docdata.h\
	$T/backends/glass/glass_document.cc\
	$T/backends/glass/glass_document.h\
	$T/backends/glass/glass_freelist.cc\
	$T/backends/glass/glass_freelist.h\
	$T/backends/glass/glass_inverter.cc\
	$T/backends/glass/glass_inverter.h\
	$T/backends/glass/glass_lazytable.h\
	$T/backends/glass/glass_metadata.cc\
	$T/backends/glass/glass_metadata.h\
	$T/backends/glass/glass_positionlist.cc\
	$T/backends/glass/glass_positionlist.h\
	$T/backends/glass/glass_postlist.cc\
	$T/backends/glass/glass_postlist.h\
	$T/backends/glass/glass_replicate_internal.h\
	$T/backends/glass/glass_spelling.cc\
	$T/backends/glass/glass_spelling.h\
	$T/backends/glass/glass_spellingwordslist.cc\
	$T/backends/glass/glass_spellingwordslist.h\
	$T/backends/glass/glass_synonym.cc\
	$T/backends/glass/glass_synonym.h\
	$T/backends/glass/glass_table.cc\
	$T/backends/glass/glass_table.h\
	$T/backends/glass/glass_termlist.cc\
	$T/backends/glass/glass_termlist.h\
	$T/backends/glass/glass_termlisttable.cc\
	$T/backends/glass/glass_termlisttable.h\
	$T/backends/glass/glass_valuelist.cc\
	$T/backends/glass/glass_valuelist.h\
	$T/backends/glass/glass_values.cc\
	$T/backends/glass/glass_values.h\
	$T/backends/glass/glass_version.cc\
	$T/backends/glass/glass_version.h\
	$T/backends/inmemory/inmemory_alltermslist.cc\
	$T/backends/inmemory/inmemory_alltermslist.h\
	$T/backends/inmemory/inmemory_database.cc\
	$T/backends/inmemory/inmemory_database.h\
	$T/backends/inmemory/inmemory_document.cc\
	$T/backends/inmemory/inmemory_document.h\
	$T/backends/inmemory/inmemory_positionlist.cc\
	$T/backends/inmemory/inmemory_positionlist.h\
	$T/backends/multi/multi_alltermslist.cc\
	$T/backends/multi/multi_alltermslist.h\
	$T/backends/multi/multi_postlist.cc\
	$T/backends/multi/multi_postlist.h\
	$T/backends/multi/multi_termlist.cc\
	$T/backends/multi/multi_termlist.h\
	$T/backends/multi/multi_valuelist.cc\
	$T/backends/multivaluelist.h\
	$T/backends/positionlist.h\
	$T/backends/prefix_compressed_strings.h\
	$T/backends/remote/net_postlist.cc\
	$T/backends/remote/net_postlist.h\
	$T/backends/remote/net_termlist.cc\
	$T/backends/remote/net_termlist.h\
	$T/backends/remote/remote-database.cc\
	$T/backends/remote/remote-database.h\
	$T/backends/remote/remote-document.cc\
	$T/backends/remote/remote-document.h\
	$T/backends/slowvaluelist.cc\
	$T/backends/slowvaluelist.h\
	$T/backends/valuelist.cc\
	$T/backends/valuelist.h\
	$T/backends/valuestats.h\
	$T/bin/xapian-check.cc\
	$T/bin/xapian-compact.cc\
	$T/bin/xapian-delve.cc\
	$T/bin/xapian-inspect.cc\
	$T/bin/xapian-progsrv.cc\
	$T/bin/xapian-replicate-server.cc\
	$T/bin/xapian-replicate.cc\
	$T/bin/xapian-tcpsrv.cc\
	$T/common/append_filename_arg.h\
	$T/common/autoptr.h\
	$T/common/bitstream.cc\
	$T/common/bitstream.h\
	$T/common/closefrom.cc\
	$T/common/closefrom.h\
	$T/common/compression_stream.cc\
	$T/common/compression_stream.h\
	$T/common/debuglog.cc\
	$T/common/debuglog.h\
	$T/common/errno_to_string.cc\
	$T/common/errno_to_string.h\
	$T/common/fd.h\
	$T/common/filetests.h\
	$T/common/fileutils.cc\
	$T/common/fileutils.h\
	$T/common/getopt.cc\
	$T/common/gnu_getopt.h\
	$T/common/internaltypes.h\
	$T/common/io_utils.cc\
	$T/common/io_utils.h\
	$T/common/keyword.cc\
	$T/common/keyword.h\
	$T/common/log2.h\
	$T/common/msvc_dirent.cc\
	$T/common/msvc_dirent.h\
	$T/common/noreturn.h\
	$T/common/omassert.cc\
	$T/common/omassert.h\
	$T/common/output-internal.h\
	$T/common/output.h\
	$T/common/pack.h\
	$T/common/posixy_wrapper.cc\
	$T/common/posixy_wrapper.h\
	$T/common/pretty.h\
	$T/common/realtime.h\
	$T/common/remoteprotocol.h\
	$T/common/replicate_utils.cc\
	$T/common/replicate_utils.h\
	$T/common/replicationprotocol.h\
	$T/common/safe.cc\
	$T/common/safedirent.h\
	$T/common/safeerrno.h\
	$T/common/safefcntl.h\
	$T/common/safenetdb.h\
	$T/common/safesysselect.h\
	$T/common/safesyssocket.h\
	$T/common/safesysstat.h\
	$T/common/safesyswait.h\
	$T/common/safeunistd.h\
	$T/common/safeuuid.h\
	$T/common/safewindows.h\
	$T/common/safewinsock2.h\
	$T/common/serialise-double.cc\
	$T/common/serialise-double.h\
	$T/common/socket_utils.cc\
	$T/common/socket_utils.h\
	$T/common/str.cc\
	$T/common/str.h\
	$T/common/stringutils.h\
	$T/common/submatch.h\
	$T/common/win32_uuid.cc\
	$T/common/wordaccess.h\
	$T/examples/copydatabase.cc\
	$T/examples/quest.cc\
	$T/examples/simpleexpand.cc\
	$T/examples/simpleindex.cc\
	$T/examples/simplesearch.cc\
	$T/examples/xapian-metadata.cc\
	$T/expand/bo1eweight.cc\
	$T/expand/esetinternal.cc\
	$T/expand/esetinternal.h\
	$T/expand/expandweight.cc\
	$T/expand/expandweight.h\
	$T/expand/ortermlist.cc\
	$T/expand/ortermlist.h\
	$T/expand/tradeweight.cc\
	$T/geospatial/geoencode.cc\
	$T/geospatial/geoencode.h\
	$T/geospatial/latlong_distance_keymaker.cc\
	$T/geospatial/latlong_metrics.cc\
	$T/geospatial/latlong_posting_source.cc\
	$T/geospatial/latlongcoord.cc\
	$(top_builddir)/languages/arabic.cc\
	$(top_builddir)/languages/arabic.h\
	$(top_builddir)/languages/armenian.cc\
	$(top_builddir)/languages/armenian.h\
	$(top_builddir)/languages/basque.cc\
	$(top_builddir)/languages/basque.h\
	$(top_builddir)/languages/catalan.cc\
	$(top_builddir)/languages/catalan.h\
	$(top_builddir)/languages/danish.cc\
	$(top_builddir)/languages/danish.h\
	$(top_builddir)/languages/dutch.cc\
	$(top_builddir)/languages/dutch.h\
	$(top_builddir)/languages/earlyenglish.cc\
	$(top_builddir)/languages/earlyenglish.h\
	$(top_builddir)/languages/english.cc\
	$(top_builddir)/languages/english.h\
	$(top_builddir)/languages/finnish.cc\
	$(top_builddir)/languages/finnish.h\
	$(top_builddir)/languages/french.cc\
	$(top_builddir)/languages/french.h\
	$(top_builddir)/languages/german.cc\
	$(top_builddir)/languages/german.h\
	$(top_builddir)/languages/german2.cc\
	$(top_builddir)/languages/german2.h\
	$(top_builddir)/languages/hungarian.cc\
	$(top_builddir)/languages/hungarian.h\
	$(top_builddir)/languages/italian.cc\
	$(top_builddir)/languages/italian.h\
	$(top_builddir)/languages/kraaij_pohlmann.cc\
	$(top_builddir)/languages/kraaij_pohlmann.h\
	$(top_builddir)/languages/lovins.cc\
	$(top_builddir)/languages/lovins.h\
	$(top_builddir)/languages/norwegian.cc\
	$(top_builddir)/languages/norwegian.h\
	$(top_builddir)/languages/porter.cc\
	$(top_builddir)/languages/porter.h\
	$(top_builddir)/languages/portuguese.cc\
	$(top_builddir)/languages/portuguese.h\
	$(top_builddir)/languages/romanian.cc\
	$(top_builddir)/languages/romanian.h\
	$(top_builddir)/languages/russian.cc\
	$(top_builddir)/languages/russian.h\
	$(top_builddir)/languages/sbl-dispatch.h\
	$(top_builddir)/languages/spanish.cc\
	$(top_builddir)/languages/spanish.h\
	$T/languages/stem.cc\
	$T/languages/steminternal.cc\
	$T/languages/steminternal.h\
	$(top_builddir)/languages/swedish.cc\
	$(top_builddir)/languages/swedish.h\
	$(top_builddir)/languages/turkish.cc\
	$(top_builddir)/languages/turkish.h\
	$T/matcher/andmaybepostlist.cc\
	$T/matcher/andmaybepostlist.h\
	$T/matcher/andnotpostlist.cc\
	$T/matcher/andnotpostlist.h\
	$T/matcher/branchpostlist.cc\
	$T/matcher/branchpostlist.h\
	$T/matcher/collapser.cc\
	$T/matcher/collapser.h\
	$T/matcher/const_database_wrapper.cc\
	$T/matcher/const_database_wrapper.h\
	$T/matcher/exactphrasepostlist.cc\
	$T/matcher/exactphrasepostlist.h\
	$T/matcher/externalpostlist.cc\
	$T/matcher/externalpostlist.h\
	$T/matcher/extraweightpostlist.h\
	$T/matcher/localsubmatch.cc\
	$T/matcher/localsubmatch.h\
	$T/matcher/maxpostlist.cc\
	$T/matcher/maxpostlist.h\
	$T/matcher/mergepostlist.cc\
	$T/matcher/mergepostlist.h\
	$T/matcher/msetcmp.cc\
	$T/matcher/msetcmp.h\
	$T/matcher/msetpostlist.cc\
	$T/matcher/msetpostlist.h\
	$T/matcher/multiandpostlist.cc\
	$T/matcher/multiandpostlist.h\
	$T/matcher/multimatch.cc\
	$T/matcher/multimatch.h\
	$T/matcher/multixorpostlist.cc\
	$T/matcher/multixorpostlist.h\
	$T/matcher/nearpostlist.cc\
	$T/matcher/nearpostlist.h\
	$T/matcher/orpostlist.cc\
	$T/matcher/orpostlist.h\
	$T/matcher/phrasepostlist.cc\
	$T/matcher/phrasepostlist.h\
	$T/matcher/queryoptimiser.h\
	$T/matcher/remotesubmatch.cc\
	$T/matcher/remotesubmatch.h\
	$T/matcher/selectpostlist.cc\
	$T/matcher/selectpostlist.h\
	$T/matcher/synonympostlist.cc\
	$T/matcher/synonympostlist.h\
	$T/matcher/valuegepostlist.cc\
	$T/matcher/valuegepostlist.h\
	$T/matcher/valuerangepostlist.cc\
	$T/matcher/valuerangepostlist.h\
	$T/matcher/valuestreamdocument.cc\
	$T/matcher/valuestreamdocument.h\
	$T/net/length.cc\
	$T/net/length.h\
	$T/net/progclient.cc\
	$T/net/progclient.h\
	$T/net/remoteconnection.cc\
	$T/net/remoteconnection.h\
	$T/net/remoteserver.cc\
	$T/net/remoteserver.h\
	$T/net/remotetcpclient.cc\
	$T/net/remotetcpclient.h\
	$T/net/remotetcpserver.cc\
	$T/net/remotetcpserver.h\
	$T/net/replicatetcpclient.cc\
	$T/net/replicatetcpclient.h\
	$T/net/replicatetcpserver.cc\
	$T/net/replicatetcpserver.h\
	$T/net/serialise-error.cc\
	$T/net/serialise-error.h\
	$T/net/serialise.cc\
	$T/net/serialise.h\
	$T/net/tcpclient.cc\
	$T/net/tcpclient.h\
	$T/net/tcpserver.cc\
	$T/net/tcpserver.h\
	$T/queryparser/cjk-tokenizer.cc\
	$T/queryparser/cjk-tokenizer.h\
	$T/queryparser/queryparser.cc\
	$(top_builddir)/queryparser/queryparser_internal.cc\
	$T/queryparser/queryparser_internal.h\
	$(top_builddir)/queryparser/queryparser_token.h\
	$T/queryparser/termgenerator.cc\
	$T/queryparser/termgenerator_internal.cc\
	$T/queryparser/termgenerator_internal.h\
	$(top_builddir)/unicode/c_istab.h\
	$T/unicode/description_append.cc\
	$T/unicode/description_append.h\
	$(top_builddir)/unicode/unicode-data.cc\
	$T/unicode/utf8itor.cc\
	$T/weight/bb2weight.cc\
	$T/weight/bm25weight.cc\
	$T/weight/boolweight.cc\
	$T/weight/dlhweight.cc\
	$T/weight/dphweight.cc\
	$T/weight/ifb2weight.cc\
	$T/weight/ineb2weight.cc\
	$T/weight/inl2weight.cc\
	$T/weight/lmweight.cc\
	$T/weight/pl2weight.cc\
	$T/weight/tfidfweight.cc\
	$T/weight/tradweight.cc\
	$T/weight/weight.cc\
	$T/weight/weightinternal.cc\
	$T/weight/weightinternal.h
