/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.4.0/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_latlongpostingsource1();
extern bool test_latlongcoords1();
extern bool test_latlongmetric1();
extern bool test_latlongmetric2();
extern bool test_latlongkeymaker1();
