/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.4.0/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_queryterms1();
extern bool test_matchall2();
extern bool test_matchnothing1();
extern bool test_overload1();
extern bool test_xor3();
extern bool test_nonutf8termdesc1();
extern bool test_queryintro1();
extern bool test_phrasealldocs1();
extern bool test_wildcard1();
extern bool test_wildcard2();
extern bool test_dualprefixwildcard1();
extern bool test_loosephrase1();
extern bool test_loosenear1();
extern bool test_complexphrase1();
extern bool test_complexnear1();
extern bool test_complexphrase2();
extern bool test_complexnear2();
