/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.4.0/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_stem1();
extern bool test_stem2();
extern bool test_stem3();
extern bool test_stemlangs2();
