/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.4.0/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_snippet1();
extern bool test_snippetstem1();
extern bool test_snippetphrase1();
extern bool test_snippetmisc1();
